import { readFileSync } from 'node:fs';
import { describe, expect, it } from 'vitest';
import { buildShoppingList } from './shopping';
import type { Meal, RecipePack } from './types';
import { UNITS } from './units';

/**
 * Contract test for the shipped recipe pack.
 *
 * The pack is generated by tools/dataset/normalise.mjs from scanned PDFs, so
 * it is the one input to this app that nobody hand-checks. These assertions
 * fail loudly if a regeneration reintroduces the problems the normaliser
 * exists to fix.
 */
const pack: RecipePack = JSON.parse(readFileSync('static/packs/my-food-bag.json', 'utf8'));

describe('shipped recipe pack', () => {
	it('parses and carries recipes', () => {
		expect(pack.version).toBe(1);
		expect(pack.recipes.length).toBeGreaterThan(200);
	});

	it('gives every recipe a unique id and a name', () => {
		const ids = pack.recipes.map((r) => r.id);
		expect(new Set(ids).size).toBe(ids.length);
		expect(pack.recipes.every((r) => r.name.trim().length > 0)).toBe(true);
		expect(pack.recipes.every((r) => r.id.trim().length > 0)).toBe(true);
	});

	it('uses only canonical units', () => {
		const used = new Set<string>();
		for (const r of pack.recipes) {
			for (const i of r.ingredients) if (i.unit) used.add(i.unit);
		}
		const unknown = [...used].filter((u) => !(u in UNITS));
		expect(unknown).toEqual([]);
	});

	it('never pairs an amount with no unit or a unit with no amount', () => {
		const broken = pack.recipes.flatMap((r) =>
			r.ingredients.filter((i) => (i.amount === null) !== (i.unit === null))
		);
		expect(broken).toEqual([]);
	});

	it('types every amount as a number, never a string', () => {
		// The original data stored "600g" as the quantity, which made the
		// shopping list sum strings.
		const bad = pack.recipes.flatMap((r) =>
			r.ingredients.filter((i) => i.amount !== null && typeof i.amount !== 'number')
		);
		expect(bad).toEqual([]);
	});

	it('explains every unquantified ingredient', () => {
		const unexplained = pack.recipes.flatMap((r) =>
			r.ingredients.filter((i) => i.amount === null && !i.note)
		);
		expect(unexplained).toEqual([]);
	});

	it('leaves no line-wrap fragments in the instructions', () => {
		// "Combine boiling water and" was a step before the normaliser ran.
		// A real step ends in punctuation; a fragment does not.
		const fragments = pack.recipes
			.flatMap((r) => r.instructions)
			.filter((s) => !/[.!?:)"']$/.test(s.text.trim()));
		expect(fragments.length).toBeLessThan(pack.recipes.length * 0.1);
	});

	it('keeps every recipe cookable: ingredients and steps present', () => {
		const empty = pack.recipes.filter((r) => !r.ingredients.length || !r.instructions.length);
		expect(empty).toEqual([]);
	});

	it('consolidates a real week of meals', () => {
		// Schedule the first seven recipes on consecutive days and check the
		// list comes out summed rather than duplicated.
		const meals: Meal[] = pack.recipes.slice(0, 7).map((r, i) => ({
			id: `m${i}`,
			recipeId: r.id,
			date: `2026-03-0${i + 2}`,
			duration: 1,
			excluded: [],
			createdAt: ''
		}));

		const list = buildShoppingList({
			meals,
			recipes: pack.recipes,
			extras: [],
			checked: new Set()
		});

		expect(list.length).toBeGreaterThan(0);
		// Every line is either summed or explained — never silently empty.
		for (const line of list) {
			expect(line.totals.length > 0 || line.unquantified.length > 0).toBe(true);
			expect(line.sources.length).toBeGreaterThan(0);
		}
		// Consolidation actually did something: fewer lines than ingredients.
		const ingredientCount = meals
			.map((m) => pack.recipes.find((r) => r.id === m.recipeId)!.ingredients.length)
			.reduce((a, b) => a + b, 0);
		expect(list.length).toBeLessThan(ingredientCount);
	});
});
