import { readFileSync } from 'node:fs';
import { describe, expect, it } from 'vitest';
import { buildShoppingList } from './shopping';
import type { Meal, RecipePack } from './types';
import { UNITS } from './units';

/**
 * Contract test for the shipped recipe pack.
 *
 * The pack is generated by tools/dataset/normalise.mjs from scanned PDFs, so
 * it is the one input to this app that nobody hand-checks. These assertions
 * fail loudly if a regeneration reintroduces the problems the normaliser
 * exists to fix.
 */
const pack: RecipePack = JSON.parse(readFileSync('static/packs/recipe-cards.json', 'utf8'));

describe('shipped recipe pack', () => {
	it('parses and carries recipes', () => {
		expect(pack.version).toBe(1);
		expect(pack.recipes.length).toBeGreaterThan(200);
	});

	it('gives every recipe a unique id and a name', () => {
		const ids = pack.recipes.map((r) => r.id);
		expect(new Set(ids).size).toBe(ids.length);
		expect(pack.recipes.every((r) => r.name.trim().length > 0)).toBe(true);
		expect(pack.recipes.every((r) => r.id.trim().length > 0)).toBe(true);
	});

	it('uses only canonical units', () => {
		const used = new Set<string>();
		for (const r of pack.recipes) {
			for (const i of r.ingredients) if (i.unit) used.add(i.unit);
		}
		const unknown = [...used].filter((u) => !(u in UNITS));
		expect(unknown).toEqual([]);
	});

	it('never pairs an amount with no unit or a unit with no amount', () => {
		const broken = pack.recipes.flatMap((r) =>
			r.ingredients.filter((i) => (i.amount === null) !== (i.unit === null))
		);
		expect(broken).toEqual([]);
	});

	it('types every amount as a number, never a string', () => {
		// The original data stored "600g" as the quantity, which made the
		// shopping list sum strings.
		const bad = pack.recipes.flatMap((r) =>
			r.ingredients.filter((i) => i.amount !== null && typeof i.amount !== 'number')
		);
		expect(bad).toEqual([]);
	});

	it('explains every unquantified ingredient', () => {
		const unexplained = pack.recipes.flatMap((r) =>
			r.ingredients.filter((i) => i.amount === null && !i.note)
		);
		expect(unexplained).toEqual([]);
	});

	it('leaves no line-wrap fragments in the instructions', () => {
		// "Combine boiling water and" was a step before the normaliser ran.
		// A real step ends in punctuation; a fragment does not.
		const fragments = pack.recipes
			.flatMap((r) => r.instructions)
			.filter((s) => !/[.!?:)"']$/.test(s.text.trim()));
		expect(fragments.length).toBeLessThan(pack.recipes.length * 0.1);
	});

	it('keeps no recipe at a size that means a serving panel survived', () => {
		// The cards print the whole ingredient list once per household size
		// (2/4/6 people). When the extractor flattened those panels a recipe
		// arrived with 58 ingredients listing the same beef mince at 300g,
		// 600g and 900g — unreadable, and it would have put 1.8kg on the
		// shopping list.
		const bloated = pack.recipes.filter((r) => r.ingredients.length > 35);
		expect(bloated.map((r) => `${r.name} (${r.ingredients.length})`)).toEqual([]);
	});

	it('does not repeat an ingredient many times within one recipe', () => {
		// A couple of repeats are normal and correct — butter for the mash and
		// butter for the sauce — and consolidation sums them. A pile of them
		// means a panel or a method echo got through.
		const repeated = pack.recipes
			.map((r) => {
				const names = r.ingredients.map((i) => i.name.toLowerCase());
				return { name: r.name, repeats: names.length - new Set(names).size };
			})
			.filter((r) => r.repeats > 6);
		expect(repeated).toEqual([]);
	});

	it('contains no recipe whose ingredients scale like serving panels', () => {
		// A surviving panel shows up as the same ingredient at amounts in a
		// clean 1:2:3 (or 1:2) progression — 300/600/900g of beef, 1/2/3 Tbsp
		// of butter — and it does that to most of the list at once.
		//
		// One ingredient alone proves nothing: a salad genuinely uses a whole
		// lemon, a quarter and a half, and that is a 1:2:4 coincidence, not a
		// panel. Requiring several ingredients to scale together separates the
		// two.
		const scalesLikePanel = (amounts: number[]) => {
			const sorted = [...amounts].sort((a, b) => a - b);
			if (sorted.length < 2 || sorted[0] <= 0) return false;
			return sorted.every((v, i) => Math.abs(v / sorted[0] - (i + 1)) < 0.01);
		};

		const suspects = pack.recipes
			.map((recipe) => {
				const byKey = new Map<string, number[]>();
				for (const i of recipe.ingredients) {
					if (i.amount === null || !i.unit) continue;
					const key = `${i.name.toLowerCase()}|${i.unit}`;
					byKey.set(key, [...(byKey.get(key) ?? []), i.amount]);
				}
				const scaling = [...byKey.values()].filter(scalesLikePanel).length;
				return { name: recipe.name, scaling };
			})
			.filter((r) => r.scaling >= 3);

		expect(suspects).toEqual([]);
	});

	it('keeps every recipe cookable: ingredients and steps present', () => {
		const empty = pack.recipes.filter((r) => !r.ingredients.length || !r.instructions.length);
		expect(empty).toEqual([]);
	});

	it('consolidates a real week of meals', () => {
		// Schedule the first seven recipes on consecutive days and check the
		// list comes out summed rather than duplicated.
		const meals: Meal[] = pack.recipes.slice(0, 7).map((r, i) => ({
			id: `m${i}`,
			recipeId: r.id,
			date: `2026-03-0${i + 2}`,
			duration: 1,
			excluded: [],
			createdAt: ''
		}));

		const list = buildShoppingList({
			meals,
			recipes: pack.recipes,
			extras: [],
			checked: new Set()
		});

		expect(list.length).toBeGreaterThan(0);
		// Every line is either summed or explained — never silently empty.
		for (const line of list) {
			expect(line.totals.length > 0 || line.unquantified.length > 0).toBe(true);
			expect(line.sources.length).toBeGreaterThan(0);
		}
		// Consolidation actually did something: fewer lines than ingredients.
		const ingredientCount = meals
			.map((m) => pack.recipes.find((r) => r.id === m.recipeId)!.ingredients.length)
			.reduce((a, b) => a + b, 0);
		expect(list.length).toBeLessThan(ingredientCount);
	});
});
